apiVersion: v2
name: mboko-frontend
description: A Helm chart for the Kamer-pro frontend service
type: application
version: 1.0.0
appVersion: "1.0.0"

sources:
  - https://github.com/ndefokou/kamer-pro

maintainers:
  - name: Tcheutchoua Ndefokou Arthur
    email: tcheutchouaarthur38@gmail.com

dependencies:
  - name: app-template
    version: "4.0.1"
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: frontend
    tags:
      - bjw
      - app

annotations:
  category: Application
