[package]
name = "kamer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
actix-web = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
bcrypt = { workspace = true }
