# Shuttle.toml
name = "kamer-pro-backend"

[env]
DATABASE_URL = "postgresql://postgres:NEW_PASSWORD@aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require&statement_cache_capacity=0"
SUPABASE_URL = "https://srymodebwnttpufrrmbm.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeW1vZGVid250dHB1ZnJybWJtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTQ2MDM3MSwiZXhwIjoyMDg1MDM2MzcxfQ.j35ttTJGkwKRxdGEjNOwxxbN3I7tgmFbFkoL7pLuAm8"
