apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-backend
  template:
    metadata:
      labels:
        app: company-backend
    spec:
      containers:
        - name: company-backend
          image: your-dockerhub-username/company-backend:latest
          ports:
            - containerPort: 8080
