---
# Source: mboko-backend/charts/backend/templates/common.yaml
apiVersion: v1
kind: Secret
metadata:
  name: le-mboko
  labels:
    app.kubernetes.io/instance: le-mboko
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: le-mboko
    helm.sh/chart: backend-4.0.1
  namespace: default
stringData:
  DATABASE_URL: postgresql://postgres.bfxkhdjgdohrziavdorf:tnarthur%40022005@aws-0-us-west-2.pooler.supabase.com:5432/postgres
  JWT_SECRET: gB0GBlpiHi6bTMHgUc60Mlc8Goo0r6tawe1s+O56bt9d5IYSILRnLbkDMlzvuhO11BT/1f9Gi76wF7Ld/dPvbg==
  S3_ACCESS_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  S3_ENDPOINT: https://bfxkhdjgdohrziavdorf.supabase.co/storage/v1/s3
  S3_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  SUPABASE_PUBLIC_URL: https://bfxkhdjgdohrziavdorf.supabase.co
---
# Source: mboko-backend/charts/backend/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: le-mboko
  labels:
    app.kubernetes.io/instance: le-mboko
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: le-mboko
    app.kubernetes.io/service: le-mboko
    helm.sh/chart: backend-4.0.1
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: le-mboko
    app.kubernetes.io/name: le-mboko
---
# Source: mboko-backend/charts/backend/templates/common.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: le-mboko
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: le-mboko
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: le-mboko
    helm.sh/chart: backend-4.0.1
  namespace: default
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: le-mboko
      app.kubernetes.io/instance: le-mboko
  template:
    metadata:
      annotations: 
        checksum/secrets: f9a52e484ec2fe17cb63b134960275301fae10036a244916c6f8c22705912bca
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: le-mboko
        app.kubernetes.io/name: le-mboko
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext: 
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers: 
        - env:
          - name: DATABASE_ACQUIRE_TIMEOUT_MS
            value: "5000"
          - name: DATABASE_MAX_CONNECTIONS
            value: "20"
          - name: FAST_START
            value: "false"
          - name: MIGRATE_ON_START
            value: "true"
          - name: RUN_MIGRATIONS
            value: "true"
          - name: S3_REGION
            value: eu-west-2
          - name: SERVER_WORKERS
            value: "2"
          - name: SKIP_DB_WAIT
            value: "false"
          - name: SUPABASE_BUCKET
            value: images
          envFrom:
          - secretRef:
              name: le-mboko
          image: ghcr.io/ndefokou/kamer-pro/backend:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          name: main
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
---
# Source: mboko-backend/charts/backend/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: le-mboko
  labels:
    app.kubernetes.io/instance: le-mboko
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: le-mboko
    helm.sh/chart: backend-4.0.1
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: "mboko-api.camer.digital"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: le-mboko
                port:
                  number: 8082
